import { LessonLayout } from '@/components/education/LessonLayout'
import { CapRateCalculator } from '@/components/calculators/CapRateCalculator'
import { NOICalculator } from '@/components/calculators/NOICalculator'
import { AnimatedExplainer } from '@/components/education/AnimatedExplainer'
import { MotionWrapper } from '@/components/education/MotionWrapper'
import { Card, CardContent } from '@/components/ui/card'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Lightbulb } from 'lucide-react'
import { notFound } from 'next/navigation'
import 'katex/dist/katex.min.css'

// Available lessons
const lessons = {
  'cap-rate-fundamentals': {
    metadata: {
      title: 'Cap Rate Fundamentals',
      summary: 'Master capitalization rate analysis for real estate investment valuation',
      order: 1,
      relatedCalculators: ['Cap Rate Calculator'],
      slug: 'cap-rate-fundamentals',
      duration: '25 min',
      difficulty: 'Intermediate' as const,
    },
    sections: [
      { id: 'concept', title: 'What is Cap Rate?', completed: false },
      { id: 'calculator', title: 'Interactive Calculator', completed: false },
      { id: 'formula', title: 'The Formula Explained', completed: false },
      { id: 'example', title: 'Worked Example', completed: false },
      { id: 'interpretation', title: 'Interpreting Results', completed: false },
      { id: 'takeaways', title: 'Key Takeaways', completed: false },
    ],
  },
  'noi-fundamentals': {
    metadata: {
      title: 'NOI Fundamentals',
      summary: 'Understanding Net Operating Income - the foundation of real estate analysis',
      order: 2,
      relatedCalculators: ['NOI Calculator'],
      slug: 'noi-fundamentals',
      duration: '30 min',
      difficulty: 'Beginner' as const,
    },
    sections: [
      { id: 'concept', title: 'What is NOI?', completed: false },
      { id: 'components', title: 'NOI Components', completed: false },
      { id: 'calculator', title: 'Interactive Calculator', completed: false },
      { id: 'example', title: 'Real-World Example', completed: false },
      { id: 'vs-cashflow', title: 'NOI vs Cash Flow', completed: false },
      { id: 'takeaways', title: 'Key Takeaways', completed: false },
    ],
  },
}

interface PageProps {
  params: Promise<{
    slug: string
  }>
}

export default async function LessonPage({ params }: PageProps) {
  const { slug } = await params
  
  const lesson = lessons[slug as keyof typeof lessons]
  
  if (!lesson) {
    notFound()
  }

  if (slug === 'noi-fundamentals') {
    return (
      <LessonLayout
        metadata={lesson.metadata}
        sections={lesson.sections}
        nextLesson={{ slug: "cap-rate-fundamentals", title: "Cap Rate Fundamentals" }}
        prevLesson={undefined}
      >
        {/* Concept Section */}
        <section id="concept" className="space-y-6 mb-12">
          <MotionWrapper
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
          >
            <h2 className="text-3xl font-bold mb-4 bg-gradient-to-r from-primary to-primary/60 bg-clip-text text-transparent">
              What is NOI?
            </h2>
            
            <Card className="p-6">
              <CardContent className="space-y-4 p-0">
                <p className="text-lg leading-relaxed">
                  <strong>Net Operating Income (NOI)</strong> is the foundation of all commercial 
                  real estate analysis. It represents the actual cash flow generated by a property 
                  after all operating expenses, but before financing costs and capital improvements.
                </p>
                
                <Alert>
                  <Lightbulb className="h-4 w-4" />
                  <AlertDescription>
                    <strong>Think of NOI as the property&apos;s &quot;true&quot; performance</strong> - it shows 
                    how much money the property makes regardless of how it&apos;s financed or owned.
                  </AlertDescription>
                </Alert>

                <div className="bg-muted/30 p-6 rounded-lg">
                  <h4 className="font-semibold mb-3">NOI Formula:</h4>
                  <div className="text-center text-2xl font-mono bg-gradient-to-r from-primary to-primary/60 bg-clip-text text-transparent">
                    NOI = Gross Income - Vacancy - Operating Expenses
                  </div>
                </div>
              </CardContent>
            </Card>
          </MotionWrapper>
        </section>

        {/* Components Section */}
        <section id="components" className="space-y-6 mb-12">
          <MotionWrapper
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            viewport={{ once: true }}
          >
            <h2 className="text-3xl font-bold mb-6">NOI Components</h2>
            
            <div className="grid gap-6 md:grid-cols-3">
              <Card className="p-4">
                <div className="text-center space-y-3">
                  <Badge className="bg-blue-100 text-blue-700 border-blue-300">
                    Gross Income
                  </Badge>
                  <div>
                    <h4 className="font-semibold mb-2">Revenue Sources</h4>
                    <ul className="text-sm text-muted-foreground space-y-1">
                      <li>• Rental income</li>
                      <li>• Parking fees</li>
                      <li>• Laundry income</li>
                      <li>• Storage fees</li>
                      <li>• Other ancillary income</li>
                    </ul>
                  </div>
                </div>
              </Card>
              
              <Card className="p-4">
                <div className="text-center space-y-3">
                  <Badge className="bg-red-100 text-red-700 border-red-300">
                    Vacancy Loss
                  </Badge>
                  <div>
                    <h4 className="font-semibold mb-2">Income Adjustments</h4>
                    <ul className="text-sm text-muted-foreground space-y-1">
                      <li>• Physical vacancy</li>
                      <li>• Economic vacancy</li>
                      <li>• Collection losses</li>
                      <li>• Typical: 3-10%</li>
                    </ul>
                  </div>
                </div>
              </Card>
              
              <Card className="p-4">
                <div className="text-center space-y-3">
                  <Badge className="bg-orange-100 text-orange-700 border-orange-300">
                    Operating Expenses
                  </Badge>
                  <div>
                    <h4 className="font-semibold mb-2">Property Costs</h4>
                    <ul className="text-sm text-muted-foreground space-y-1">
                      <li>• Property taxes</li>
                      <li>• Insurance</li>
                      <li>• Property management</li>
                      <li>• Maintenance & repairs</li>
                      <li>• Utilities (if owner-paid)</li>
                    </ul>
                  </div>
                </div>
              </Card>
            </div>
          </MotionWrapper>
        </section>

        {/* Calculator Section */}
        <section id="calculator" className="mb-12">
          <MotionWrapper
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.4 }}
            viewport={{ once: true }}
          >
            <h2 className="text-3xl font-bold mb-6">Interactive NOI Calculator</h2>
            <p className="text-muted-foreground mb-6">
              Use this calculator to analyze property income and expenses. 
              Adjust the inputs to see how different factors affect NOI.
            </p>
            
            <NOICalculator embedded={false} />
          </MotionWrapper>
        </section>

        {/* Real-World Example */}
        <section id="example" className="mb-12">
          <MotionWrapper
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.6 }}
            viewport={{ once: true }}
          >
            <h2 className="text-3xl font-bold mb-6">Real-World Example</h2>
            
            <Card className="p-6">
              <CardContent className="space-y-6 p-0">
                <div className="bg-muted/30 p-6 rounded-lg">
                  <h4 className="font-semibold mb-4">🏢 20-Unit Apartment Building</h4>
                  
                  <div className="grid md:grid-cols-2 gap-6">
                    <div>
                      <h5 className="font-medium mb-3">Income Analysis:</h5>
                      <ul className="space-y-2 text-sm">
                        <li><strong>20 units × $1,500/month:</strong> $360,000/year</li>
                        <li><strong>Parking/laundry income:</strong> $12,000/year</li>
                        <li><strong>Gross Income:</strong> $372,000</li>
                        <li><strong>Vacancy (5%):</strong> -$18,600</li>
                        <li className="pt-2 border-t"><strong>Effective Gross Income:</strong> $353,400</li>
                      </ul>
                    </div>
                    
                    <div>
                      <h5 className="font-medium mb-3">Operating Expenses:</h5>
                      <div className="space-y-2 text-sm font-mono">
                        <div>Property taxes: $28,000</div>
                        <div>Insurance: $8,500</div>
                        <div>Property management: $21,200</div>
                        <div>Utilities: $15,600</div>
                        <div>Maintenance: $18,200</div>
                        <div>Other expenses: $6,500</div>
                        <div className="pt-2 border-t">
                          <strong>Total Expenses: $98,000</strong>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  <Alert className="mt-4">
                    <AlertDescription>
                      <strong>Final NOI:</strong> $353,400 - $98,000 = <span className="text-2xl font-bold text-primary">$255,400</span>
                    </AlertDescription>
                  </Alert>
                </div>
              </CardContent>
            </Card>
          </MotionWrapper>
        </section>

        {/* NOI vs Cash Flow */}
        <section id="vs-cashflow" className="mb-12">
          <MotionWrapper
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.8 }}
            viewport={{ once: true }}
          >
            <h2 className="text-3xl font-bold mb-6">NOI vs Cash Flow</h2>
            
            <div className="grid gap-6 md:grid-cols-2">
              <Card className="p-6">
                <div className="text-center space-y-4">
                  <Badge className="bg-blue-100 text-blue-700 border-blue-300 text-base">
                    Net Operating Income (NOI)
                  </Badge>
                  <div>
                    <h4 className="font-semibold mb-3">Property Performance</h4>
                    <div className="text-2xl font-mono mb-3">Income - Operating Expenses</div>
                    <ul className="text-sm text-muted-foreground space-y-1">
                      <li>• Independent of financing</li>
                      <li>• Compares property-to-property</li>
                      <li>• Used for cap rates</li>
                      <li>• Before debt service</li>
                    </ul>
                  </div>
                </div>
              </Card>
              
              <Card className="p-6">
                <div className="text-center space-y-4">
                  <Badge className="bg-green-100 text-green-700 border-green-300 text-base">
                    Cash Flow
                  </Badge>
                  <div>
                    <h4 className="font-semibold mb-3">Investment Performance</h4>
                    <div className="text-2xl font-mono mb-3">NOI - Debt Service</div>
                    <ul className="text-sm text-muted-foreground space-y-1">
                      <li>• Depends on financing</li>
                      <li>• Investor-specific</li>
                      <li>• After debt payments</li>
                      <li>• Shows actual returns</li>
                    </ul>
                  </div>
                </div>
              </Card>
            </div>

            <Alert className="mt-6">
              <AlertDescription>
                <strong>Key Insight:</strong> NOI shows how well the property performs, 
                while cash flow shows how well your investment performs. Both are important 
                but serve different purposes in analysis.
              </AlertDescription>
            </Alert>
          </MotionWrapper>
        </section>

        {/* Key Takeaways */}
        <section id="takeaways" className="mb-12">
          <MotionWrapper
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 1.0 }}
            viewport={{ once: true }}
          >
            <h2 className="text-3xl font-bold mb-6">Key Takeaways</h2>
            
            <Card className="p-6">
              <CardContent className="p-0">
                <div className="grid gap-6 md:grid-cols-2">
                  <div>
                    <h4 className="font-semibold mb-3">✅ Remember:</h4>
                    <ul className="space-y-2 text-sm">
                      <li>• NOI is before financing - it&apos;s property performance</li>
                      <li>• Always include vacancy allowances</li>
                      <li>• Verify operating expenses carefully</li>
                      <li>• Don&apos;t include debt service or capital improvements</li>
                      <li>• Use NOI for cap rates and property comparisons</li>
                    </ul>
                  </div>
                  
                  <div>
                    <h4 className="font-semibold mb-3">⚠️ Common Mistakes:</h4>
                    <ul className="space-y-2 text-sm">
                      <li>• Including debt payments in operating expenses</li>
                      <li>• Forgetting vacancy reserves</li>
                      <li>• Mixing capital improvements with repairs</li>
                      <li>• Using pro forma instead of actual expenses</li>
                      <li>• Comparing NOI to cash flow incorrectly</li>
                    </ul>
                  </div>
                </div>
                
                <Alert className="mt-6">
                  <AlertDescription>
                    <strong>Next Steps:</strong> Practice with the NOI calculator above, then 
                    explore cap rate analysis to see how NOI drives property valuation.
                  </AlertDescription>
                </Alert>
              </CardContent>
            </Card>
          </MotionWrapper>
        </section>
      </LessonLayout>
    )
  }

  if (slug === 'cap-rate-fundamentals') {
    return (
      <LessonLayout
        metadata={lesson.metadata}
        sections={lesson.sections}
        nextLesson={undefined}
        prevLesson={{ slug: "noi-fundamentals", title: "NOI Fundamentals" }}
      >
        {/* Concept Section */}
        <section id="concept" className="space-y-6 mb-12">
          <MotionWrapper
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
          >
            <h2 className="text-3xl font-bold mb-4 bg-gradient-to-r from-primary to-primary/60 bg-clip-text text-transparent">
              What is Cap Rate?
            </h2>
            
            <Card className="p-6">
              <CardContent className="space-y-4 p-0">
                <p className="text-lg leading-relaxed">
                  The <strong>Capitalization Rate (Cap Rate)</strong> is one of the most fundamental 
                  metrics in real estate investment analysis. It measures the relationship between 
                  a property&apos;s Net Operating Income (NOI) and its market value or purchase price.
                </p>
                
                <Alert>
                  <Lightbulb className="h-4 w-4" />
                  <AlertDescription>
                    <strong>Think of cap rate as the &quot;yield&quot; of a property</strong> - similar to how 
                    you might evaluate a bond or stock dividend yield. It tells you what percentage 
                    return you can expect from the property&apos;s operating income.
                  </AlertDescription>
                </Alert>

                <div className="bg-muted/30 p-6 rounded-lg">
                  <h4 className="font-semibold mb-3">Cap Rate in Simple Terms:</h4>
                  <ul className="space-y-2 text-muted-foreground">
                    <li>• <strong>High Cap Rate (8%+):</strong> Higher returns, potentially higher risk</li>
                    <li>• <strong>Medium Cap Rate (5-8%):</strong> Balanced risk and return</li>
                    <li>• <strong>Low Cap Rate (&lt;5%):</strong> Lower returns, typically lower risk</li>
                  </ul>
                </div>
              </CardContent>
            </Card>
          </MotionWrapper>
        </section>

        {/* Calculator Section */}
        <section id="calculator" className="mb-12">
          <MotionWrapper
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            viewport={{ once: true }}
          >
            <h2 className="text-3xl font-bold mb-6">Interactive Calculator</h2>
            <p className="text-muted-foreground mb-6">
              Use this calculator to explore how NOI and property price affect cap rates. 
              Try different scenarios to see the sensitivity analysis.
            </p>
            
            <CapRateCalculator embedded={false} />
          </MotionWrapper>
        </section>

        {/* Formula Section */}
        <section id="formula" className="mb-12">
          <MotionWrapper
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.4 }}
            viewport={{ once: true }}
          >
            <h2 className="text-3xl font-bold mb-6">The Formula Explained</h2>
            
            <AnimatedExplainer title="Cap Rate Formula">
              <div className="text-center space-y-6">
                <div className="text-4xl font-mono bg-gradient-to-r from-primary to-primary/60 bg-clip-text text-transparent">
                  Cap Rate = NOI ÷ Property Value
                </div>
                
                <div className="grid md:grid-cols-2 gap-6 mt-8">
                  <div className="p-4 bg-blue-50 dark:bg-blue-950/30 rounded-lg">
                    <h4 className="font-semibold text-blue-700 dark:text-blue-300 mb-2">
                      Net Operating Income (NOI)
                    </h4>
                    <ul className="text-sm space-y-1 text-muted-foreground">
                      <li>• Annual rental income</li>
                      <li>• Minus vacancy losses</li>
                      <li>• Minus operating expenses</li>
                      <li>• Excludes debt service</li>
                    </ul>
                  </div>
                  
                  <div className="p-4 bg-green-50 dark:bg-green-950/30 rounded-lg">
                    <h4 className="font-semibold text-green-700 dark:text-green-300 mb-2">
                      Property Value
                    </h4>
                    <ul className="text-sm space-y-1 text-muted-foreground">
                      <li>• Purchase price, or</li>
                      <li>• Current market value</li>
                      <li>• Total acquisition cost</li>
                      <li>• Basis for comparison</li>
                    </ul>
                  </div>
                </div>
              </div>
            </AnimatedExplainer>
          </MotionWrapper>
        </section>

        {/* Example Section */}
        <section id="example" className="mb-12">
          <MotionWrapper
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.6 }}
            viewport={{ once: true }}
          >
            <h2 className="text-3xl font-bold mb-6">Worked Example</h2>
            
            <Card className="p-6">
              <CardContent className="space-y-6 p-0">
                <div className="bg-muted/30 p-6 rounded-lg">
                  <h4 className="font-semibold mb-4">🏢 Office Building Analysis</h4>
                  
                  <div className="grid md:grid-cols-2 gap-6">
                    <div>
                      <h5 className="font-medium mb-3">Property Information:</h5>
                      <ul className="space-y-2 text-sm">
                        <li><strong>Purchase Price:</strong> $1,250,000</li>
                        <li><strong>Gross Rental Income:</strong> $180,000/year</li>
                        <li><strong>Vacancy Rate:</strong> 5%</li>
                        <li><strong>Operating Expenses:</strong> $45,000/year</li>
                      </ul>
                    </div>
                    
                    <div>
                      <h5 className="font-medium mb-3">Calculation Steps:</h5>
                      <div className="space-y-2 text-sm font-mono">
                        <div>Effective Income: $180,000 × 0.95 = $171,000</div>
                        <div>NOI: $171,000 - $45,000 = $126,000</div>
                        <div className="pt-2 border-t">
                          <strong>Cap Rate: $126,000 ÷ $1,250,000 = 10.08%</strong>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  <Alert className="mt-4">
                    <AlertDescription>
                      <strong>Analysis:</strong> A 10.08% cap rate is relatively high, suggesting 
                      either strong income potential or higher risk factors. Compare this to 
                      similar properties in the market to determine attractiveness.
                    </AlertDescription>
                  </Alert>
                </div>
              </CardContent>
            </Card>
          </MotionWrapper>
        </section>

        {/* Interpretation Section */}
        <section id="interpretation" className="mb-12">
          <MotionWrapper
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.8 }}
            viewport={{ once: true }}
          >
            <h2 className="text-3xl font-bold mb-6">Interpreting Cap Rate Results</h2>
            
            <div className="grid gap-6 md:grid-cols-3">
              <Card className="p-4">
                <div className="text-center space-y-3">
                  <Badge className="bg-red-100 text-red-700 border-red-300">
                    High Cap Rate (8%+)
                  </Badge>
                  <div>
                    <h4 className="font-semibold mb-2">Higher Returns</h4>
                    <ul className="text-sm text-muted-foreground space-y-1">
                      <li>• Higher risk properties</li>
                      <li>• Emerging markets</li>
                      <li>• Value-add opportunities</li>
                      <li>• Older buildings</li>
                    </ul>
                  </div>
                </div>
              </Card>
              
              <Card className="p-4">
                <div className="text-center space-y-3">
                  <Badge className="bg-yellow-100 text-yellow-700 border-yellow-300">
                    Medium Cap Rate (5-8%)
                  </Badge>
                  <div>
                    <h4 className="font-semibold mb-2">Balanced Investment</h4>
                    <ul className="text-sm text-muted-foreground space-y-1">
                      <li>• Stable markets</li>
                      <li>• Quality properties</li>
                      <li>• Predictable income</li>
                      <li>• Moderate appreciation</li>
                    </ul>
                  </div>
                </div>
              </Card>
              
              <Card className="p-4">
                <div className="text-center space-y-3">
                  <Badge className="bg-green-100 text-green-700 border-green-300">
                    Low Cap Rate (&lt;5%)
                  </Badge>
                  <div>
                    <h4 className="font-semibold mb-2">Lower Risk</h4>
                    <ul className="text-sm text-muted-foreground space-y-1">
                      <li>• Prime locations</li>
                      <li>• High-quality tenants</li>
                      <li>• Appreciation potential</li>
                      <li>• Institutional grade</li>
                    </ul>
                  </div>
                </div>
              </Card>
            </div>
          </MotionWrapper>
        </section>

        {/* Key Takeaways */}
        <section id="takeaways" className="mb-12">
          <MotionWrapper
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 1.0 }}
            viewport={{ once: true }}
          >
            <h2 className="text-3xl font-bold mb-6">Key Takeaways</h2>
            
            <Card className="p-6">
              <CardContent className="p-0">
                <div className="grid gap-6 md:grid-cols-2">
                  <div>
                    <h4 className="font-semibold mb-3">✅ Remember:</h4>
                    <ul className="space-y-2 text-sm">
                      <li>• Cap rates reflect risk-return relationships</li>
                      <li>• Compare to market standards for context</li>
                      <li>• Higher cap rates aren&apos;t always better</li>
                      <li>• Consider income growth potential</li>
                      <li>• Use with other analysis metrics</li>
                    </ul>
                  </div>
                  
                  <div>
                    <h4 className="font-semibold mb-3">⚠️ Limitations:</h4>
                    <ul className="space-y-2 text-sm">
                      <li>• Ignores financing and tax benefits</li>
                      <li>• Doesn&apos;t account for appreciation</li>
                      <li>• Based on current NOI snapshot</li>
                      <li>• Market conditions affect interpretation</li>
                      <li>• Property-specific factors matter</li>
                    </ul>
                  </div>
                </div>
                
                <Alert className="mt-6">
                  <AlertDescription>
                    <strong>Next Steps:</strong> Practice with the calculator above using different 
                    scenarios. Then explore NOI analysis and cash flow modeling to build a complete 
                    investment picture.
                  </AlertDescription>
                </Alert>
              </CardContent>
            </Card>
          </MotionWrapper>
        </section>
      </LessonLayout>
    )
  }

  return notFound()
}